spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
#        - id: main_service_route
#          uri: lb://main-service
#          predicates:
#            - Path=/**
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request_service_route
          uri: lb:/request-service
          predicates:
            - Path=/users/*/requests/**

server:
  port: 8080