spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: stat
    password: stat
    driver-class-name: org.postgresql.Driver