DROP TABLE IF EXISTS user_action;

CREATE TABLE IF NOT EXISTS user_action (
user_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
weight DOUBLE PRECISION NOT NULL,
updated TIMESTAMP NOT NULL,
PRIMARY KEY (user_id, event_id)
);

--CREATE TABLE IF EXISTS
